version: '3'
services:
  sp:
    build: ./sp
    container_name: dojo-sp
  apache:
    build: ./apache
    container_name: dojo-apache
    environment:
      - IDP_DOMAIN=${IDP_DOMAIN}
    ports:
      - "80:80"
