version: '3.1'
services:
  sp:
    build: ./sp
    container_name: dojo-sp
  apache:
    build:
      context: ./apache
      args:
        LOCAL_CONFIG_DIR: ${LOCAL_CONFIG_DIR:-./config}
    container_name: dojo-apache
    environment:
      IDP_DOMAIN: ${IDP_DOMAIN}
      IDP_HTTP_REDIRECT_PATH: ${IDP_HTTP_REDIRECT_PATH}
      IDP_PORT: ${IDP_PORT}
      SP_PORT: ${SP_PORT}
      SP_PROTOCOL: ${SP_PROTOCOL}
    ports:
      - "80:80"
      - "8080:8080"
      - "8443:8443"